/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsimpresos;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author luis-pc
 */
public class CambiarEstadoNota extends javax.swing.JFrame {
    Nota nota;
    double saldoCuenta =0;
    VerNota frameAnterior;
    VerNotas frameVerNotas;
    
    public CambiarEstadoNota(Nota nota, VerNota frameAnterior, VerNotas frameVerNotas) {
        initComponents();
        this.frameAnterior = frameAnterior;
        this.frameVerNotas = frameVerNotas;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.nota = nota;
        TitledBorder tb = BorderFactory.createTitledBorder("Nota No. "+nota.getIdNota());
        pnlTitulo.setBorder(tb);
//        lblNota.setText("No. de nota : "+nota.getIdNota());
        if(nota.getCliente()!=null){
            if (nota.getCliente().getId() != 2) {
                Miembro aux = nota.getCliente();
                lblUsuario.setText("Cliente : "+aux.getNombres()+ " "+aux.getApPaterno()+" " + nota.getCliente().getApMaterno());
                lblMiembro.setText("Miembro : si");
                lblTarjeta.setText("No. de tarjeta : "+ aux.getNumeroTarjeta());
                lblSaldoTarjeta.setText("Saldo en tarjeta : $"+aux.getSaldo());
            }else{
                lblUsuario.setText("Cliente : "+nota.getCliente().getNombres()+ " "+nota.getCliente().getApPaterno()+" " + nota.getCliente().getApMaterno());
                lblMiembro.setText("Este cliente no es un miembro");
                lblTarjeta.setText("Sin número de tarjeta");
                lblSaldoTarjeta.setText("Saldo inexistente");
            }
        }else{
            lblUsuario.setText("Cliente : "+nota.getNombres()+ " "+nota.getApPaterno()+" " + nota.getApMaterno());
            lblMiembro.setText("Este cliente no es un miembro");
            lblTarjeta.setText("Sin número de tarjeta");
            lblSaldoTarjeta.setText("Saldo inexistente");
        }
        double totalCuenta =0;
        for (int i = 0; i < nota.getArticulos().size(); i++) {
            totalCuenta+= nota.getArticulos().get(i).getPrecio()* nota.getArticulos().get(i).getCantidad();
        }
        double totalPagos = 0;
        for (int i = 0; i < nota.getAbonos().size(); i++) {
            totalPagos+= nota.getAbonos().get(i).getMonto();
            
        }
        saldoCuenta = totalCuenta-totalPagos;
        lblSaldoCuenta.setText("Saldo de la cuenta : $"+saldoCuenta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTarjeta = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSaldoTarjeta = new javax.swing.JLabel();
        lblSaldoCuenta = new javax.swing.JLabel();
        lblMiembro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        optUno = new javax.swing.JRadioButton();
        optDos = new javax.swing.JRadioButton();
        optTres = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambio de estado para nota");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota no. x"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cliente"));

        lblTarjeta.setText("jLabel1");

        lblUsuario.setText("jLabel1");

        lblSaldoTarjeta.setText("jLabel1");

        lblSaldoCuenta.setText("jLabel2");

        lblMiembro.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMiembro)
                    .addComponent(lblSaldoCuenta)
                    .addComponent(lblSaldoTarjeta)
                    .addComponent(lblTarjeta)
                    .addComponent(lblUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMiembro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado de nota"));

        btnGrupo.add(optUno);
        optUno.setText("En Espera");

        btnGrupo.add(optDos);
        optDos.setText("En Proceso");

        btnGrupo.add(optTres);
        optTres.setText("Terminada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optUno)
                    .addComponent(optDos)
                    .addComponent(optTres))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(optUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optTres)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (optUno.isSelected()) {
            if (new ConexionNotas().ponerEnEsperaNota(nota)) {
                JOptionPane.showMessageDialog(null, "El estado de la nota fue actualizado correctamente");
                frameVerNotas.actualizarNotas(new ConexionNotas().obtenerVistaNotas());
                this.dispose();
            }
        }else if (optDos.isSelected()) {
            if (new ConexionNotas().ponerEnProcesoNota(nota)) {
                JOptionPane.showMessageDialog(null, "El estado de la nota fue actualizado correctamente");
                frameVerNotas.actualizarNotas(new ConexionNotas().obtenerVistaNotas());
                this.dispose();
            }
        }else if(optTres.isSelected()){
            if (new ConexionNotas().terminarNota(nota)) {
                JOptionPane.showMessageDialog(null, "El estado de la nota fue actualizado correctamente");
                frameVerNotas.actualizarNotas(new ConexionNotas().obtenerVistaNotas());
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar una opción");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMiembro;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JLabel lblSaldoTarjeta;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JRadioButton optDos;
    private javax.swing.JRadioButton optTres;
    private javax.swing.JRadioButton optUno;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
