/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsimpresos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luis-pc
 */
public class HacerPago extends javax.swing.JFrame {
    Nota nota;
    double saldoCuenta =0;
    Abono nuevo=null; 
    VerNota frameAnterior;
    boolean terminar = false;
    public HacerPago(Nota nota, VerNota frameAnterior, boolean terminar) {
        initComponents();
        this.frameAnterior = frameAnterior;
        this.terminar = terminar;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.nota = nota;
        lblNota.setText("No. de nota : "+nota.getIdNota());
        if(nota.getCliente()!=null){
            Miembro aux = nota.getCliente();
            lblUsuario.setText("Cliente : "+aux.getNombres()+ " "+aux.getApPaterno());
            lblMiembro.setText("Miembro : si");
            lblTarjeta.setText("No. de tarjeta : "+ aux.getNumeroTarjeta());
            lblSaldoTarjeta.setText("Saldo en tarjeta : $"+aux.getSaldo());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmbTipoPago.getModel();
            modelo.addElement("Tarjeta miembro");
        }else{
            lblUsuario.setText("Cliente : "+nota.getNombres()+ " "+nota.getApPaterno());
            lblMiembro.setText("Miembro : no");
            lblTarjeta.setText("No. de tarjeta : ");
            lblSaldoTarjeta.setText("Saldo en tarjeta : ");
        }
        double totalCuenta =0;
        for (int i = 0; i < nota.getArticulos().size(); i++) {
            totalCuenta+= nota.getArticulos().get(i).getPrecio()* nota.getArticulos().get(i).getCantidad();
        }
        double totalPagos = 0;
        for (int i = 0; i < nota.getAbonos().size(); i++) {
            totalPagos+= nota.getAbonos().get(i).getMonto();
            
        }
        saldoCuenta = totalCuenta-totalPagos;
        lblSaldoCuenta.setText("Saldo de la cuenta : $"+saldoCuenta);
        if(terminar){
            btnAceptar.setText("Aceptar y terminar");
            txtCantidad.setText(saldoCuenta+"");
        }
    }
    private boolean isNumber(String cadena){
         try {
             Double.parseDouble(cadena.replace(",", ""));
         } catch (NumberFormatException nfe){
             String newCadena = cadena.replace(".", "").replace(',', '.');
             try{
                 Double.parseDouble(newCadena);
             } catch (NumberFormatException nfe2){
                 return false;
             }
        }
         return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNota = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        lblSaldoTarjeta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoPago = new javax.swing.JComboBox();
        lblSaldoCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMiembro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNota.setText("jLabel1");

        lblUsuario.setText("jLabel1");

        lblTarjeta.setText("jLabel1");

        lblSaldoTarjeta.setText("jLabel1");

        jLabel1.setText("Tipo de pago :");

        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo" }));

        lblSaldoCuenta.setText("jLabel2");

        jLabel2.setText("Cantidad :");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblMiembro.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMiembro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(lblSaldoCuenta)
                    .addComponent(lblSaldoTarjeta)
                    .addComponent(lblTarjeta)
                    .addComponent(lblUsuario)
                    .addComponent(lblNota)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoPago, 0, 143, Short.MAX_VALUE)
                            .addComponent(txtCantidad))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMiembro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoCuenta)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(!txtCantidad.getText().equals("")&&txtCantidad.getText()!=null){
            if(isNumber(txtCantidad.getText())){
                if(Double.parseDouble(txtCantidad.getText())<=saldoCuenta){
                    if(cmbTipoPago.getSelectedIndex()==1){
                        if(nota.getCliente().getSaldo()>=saldoCuenta){
                            nuevo = new Abono(nota.getIdNota(), Double.parseDouble(txtCantidad.getText()),"Tarjeta","no","");
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "El saldo de la tarjeta no es suficiente");
                        }
                        
                    }else{
                        nuevo = new Abono(nota.getIdNota(), Double.parseDouble(txtCantidad.getText()),"Efectivo","no","");
                    }
                    ConexionNotas conexion = new ConexionNotas();
                    conexion.guardarAbono(nuevo);
                    frameAnterior.actualizarPagos(conexion.obtenerAbonosPorId(nuevo.getId()));
                    if(terminar){
                        conexion.terminarNota(nota);
                    }
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "La cantidad es mayor al saldo de la cuenta");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El campo Cantidad debe ser numérico");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HacerPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMiembro;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JLabel lblSaldoTarjeta;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
