/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsimpresos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis-pc
 */
public class VerNota extends javax.swing.JFrame {

    Nota nota;
    double total = 0;
    double totalAbonos = 0;

    /**
     * Creates new form VerNota
     */
    public VerNota(int idNota) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        nota = (new ConexionNotas()).getNotaPorId(idNota);
        if (nota != null) {
            lblId.setText("No. de nota " + nota.getIdNota());
            lblFecha.setText("Fecha: " + nota.getFecha());
            if (nota.getFechaEntrega() != null && !nota.getFechaEntrega().equals("")) {
                lblFechaEntrega.setText("Fecha entrega :" + nota.getFechaEntrega());
            } else {
                lblFechaEntrega.setText("Fecha entrega : No capturada");
            }

            if (nota.getCliente() != null) {
                lblNombre.setText("Nombre: " + nota.getCliente().getNombres() + " " + nota.getCliente().getApPaterno());
                lblDomicilio.setText("Domicilio: " + nota.getCliente().getDomicilio());
                lblTelefono.setText("Teléfono: " + nota.getCliente().getTelefono());

            } else {
                lblNombre.setText("Nombre: " + nota.getNombres() + " " + nota.getApPaterno() + " " + nota.getApMaterno());
                lblDomicilio.setText("Domicilio: Roble no. 9");
                lblTelefono.setText("Teléfono: " + nota.getTelefono());
            }

            String[] columnas = {"Servicio", "Precio", "Cantidad", "Total"};
            DefaultTableModel model1 = new DefaultTableModel(columnas, 0) {
                @Override
                public boolean isCellEditable(int row, int col) {
                    return false;
                }
            };

            for (int i = 0; i < nota.getArticulos().size(); i++) {
                Object[] obj = {nota.getArticulos().get(i).getServicio(), nota.getArticulos().get(i).getPrecio(), nota.getArticulos().get(i).getCantidad(), (nota.getArticulos().get(i).getCantidad() * nota.getArticulos().get(i).getPrecio())};
                model1.addRow(obj);
                total += nota.getArticulos().get(i).getCantidad() * nota.getArticulos().get(i).getPrecio();
            }
            Object[] objTotal = {"", "", "Total", "$" + total};
            model1.addRow(objTotal);
            tableArticulos.setModel(model1);
            actualizarPagos(nota.getAbonos());
            if (nota.getObservaciones() != null && !nota.getObservaciones().equals("")) {
                lblObservaciones.setText("Observaciones: " + nota.getObservaciones());
            } else {
                lblObservaciones.setText("No hay observaciones en esta nota");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al abrir nota");
        }

    }

    public void actualizarPagos(ArrayList<Abono> abonos) {
        String[] columnas2 = {"Fecha", "Tipo pago", "Monto"};
        DefaultTableModel model2 = new DefaultTableModel(columnas2, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        totalAbonos = 0;
        for (int i = 0; i < abonos.size(); i++) {
            Object[] obj = {abonos.get(i).getFecha(), abonos.get(i).getTipoPago(), abonos.get(i).getMonto()};
            model2.addRow(obj);
            totalAbonos += abonos.get(i).getMonto();
        }
        Object[] objAbonos = {"", "Total", "$" + totalAbonos};
        Object[] objSaldo = {"", "Saldo a pagar", "$" + (total - totalAbonos)};
        model2.addRow(objAbonos);
        model2.addRow(objSaldo);
        tableAbonos.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        lblFechaEntrega1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblTelefono1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticulos = new javax.swing.JTable();
        lblTelefono2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAbonos = new javax.swing.JTable();
        lblObservaciones = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblId.setText("jLabel1");

        lblFecha.setText("jLabel1");

        lblFechaEntrega.setText("jLabel1");

        lblFechaEntrega1.setText("Datos del cliente");

        lblNombre.setText("jLabel1");

        lblDomicilio.setText("jLabel1");

        lblTelefono.setText("jLabel1");

        lblTelefono1.setText("Artículos de la nota");

        tableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableArticulos);

        lblTelefono2.setText("Pagos de la nota");

        tableAbonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableAbonos);

        lblObservaciones.setText("jLabel1");

        btnPago.setText("Hacer pago");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar nota");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnPago)
                        .addGap(18, 18, 18)
                        .addComponent(btnTerminar))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lblTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addGap(18, 18, 18)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefono1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTelefono2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPago)
                    .addComponent(btnTerminar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        HacerPago nuevo = new HacerPago(nota, this, false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        if (total > totalAbonos) {
            int respuesta = JOptionPane.showConfirmDialog(null, "La cuenta tiene un saldo de $" + (total - totalAbonos) + " ¿Desea realizar ese pago en este instante?");
            if (respuesta == 0) {
                HacerPago nuevo = new HacerPago(nota, this, true);
                nuevo.setVisible(true);
            } else {
                int respuesta2 = JOptionPane.showConfirmDialog(null, "Se terminará la cuenta con un adeudo, ¿Desea continuar?");
                if(respuesta2==0){
                    (new ConexionNotas()).terminarNota(nota);
                }
            }
        } else {
            int respuesta2 = JOptionPane.showConfirmDialog(null, "¿Seguro que desea terminar la cuenta?");
            if(respuesta2==0){
                (new ConexionNotas()).terminarNota(nota);
            }
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaEntrega1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tableAbonos;
    private javax.swing.JTable tableArticulos;
    // End of variables declaration//GEN-END:variables
}
